### ISSUE TITLE
Add OAuth extension to php

### ISSUE THREAD

**Issue by samlerner** [Wodby/drupal-php#12]
We need the OAuth php extension for our `docker4drupal` setup.

https://pecl.php.net/package/oauth

Is there a way to add this ourselves to our `docker-compose.yml`, or does it need to be part of the main package?

**Comment by PavelPrischepa** [comment]
OAuth has been added but only for PHP7 because there is no oauth alpine package for PHP5.6

**Comment by mcdruid** [comment]
To install the OAuth extension in the PHP5.6 container:

`# apk add --update php5-dev alpine-sdk autoconf && pecl install oauth-1.2.3`

**Comment by csandanov** [comment]
@mcdruid PHP 5.6 already comes with installed OAuth extension https://github.com/wodby/php/blob/master/5.6/Dockerfile#L117

**Comment by mcdruid** [comment]
@csandanov thanks!
