### ISSUE TITLE
Upgrade to php 7.1

### ISSUE THREAD

**Issue by shrop** [wodby/drupal-php#17]
From what I understand, PHP 7.1 has some security fixes. 

http://www.php.net/ChangeLog-7.php#7.1.0

**Comment by shrop** [comment]
Though I can't seem to ID the commits where they were updated.

**Comment by PavelPrischepa** [comment]
We use php 7.0 in D4D because there is no 7.1 in alpine [packages](https://pkgs.alpinelinux.org/packages?name=php7&branch=&repo=&arch=&maintainer=).

**Comment by shrop** [comment]
gotcha.. thanks!
