### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by mkdok** [wodby/drupal-php#18]
Can you add support for PostgreSQL inside PHP container, please?

**Comment by PavelPrischepa** [comment]
I've added php-pgsql and php-pdo_pgsql both for PHP 5.6 and 7.0.

**Comment by mkdok** [comment]
Thanks a lot. Can you also add postgresql-client (as we have client for MariaDB)?

**Comment by PavelPrischepa** [comment]
Done.
