### ISSUE TITLE
Increate memory size

### ISSUE THREAD

**Issue by RobLoach** [wodby/drupal-php#19]
The default of 512 is sometimes not enough. Would be great to double it.

**Comment by PavelPrischepa** [comment]
I've increased memory_limit up to 1024M. Affected images:
```
wodby/drupal-php:latest
wodby/drupal-php:7.0
wodby/drupal-php:5.6
```

**Comment by RobLoach** [comment]
Thanks so much, @PavelPrischepa!

**Comment by GTSLiDe** [comment]
@PavelPrischepa  , I tried updating the image to the latest, 7.0-2.4.9, or 7.1-2.4.9 but still it's showing 512MB memory_limit. Can you help?

**Comment by PavelPrischepa** [comment]
@GTSLiDe in the 2.x version of d4d you should use `PHP_MEMORY_LIMIT` [environment variable](https://github.com/wodby/php#environment-variables) to customize memory limit.

**Comment by GTSLiDe** [comment]
@PavelPrischepa it worked! thank you so much!
