### ISSUE TITLE
Add pecl YAML

### ISSUE THREAD

**Issue by larowlan** [wodby/drupal-php#20]
Drupal 8 will use the pecl yaml extension over the symfony Yaml parser if the extension is present.

This leads to significant performance improvements.

Many production hosting environments will use the pecl yaml extension.

There are some syntax differences between the two.

Not having it in development (local docker) can lead to issues when deploying to production as yaml parsing errors may occur.

**Comment by larowlan** [comment]
Working on PR

**Comment by larowlan** [comment]
See #21

**Comment by PavelPrischepa** [comment]
PR #21 has been merged.

**Comment by csandanov** [comment]
YAML extension has been added for all versions (https://github.com/wodby/php/blob/master/7.0/test/php_modules)
