### ISSUE TITLE
Add PHP LDAP module

### ISSUE THREAD

**Issue by pixelcat** [wodby/drupal-php#25]
Please review pull request:

https://github.com/wodby/drupal-php/pull/24

This adds ldap support to the docker image for php 5.6, 7.0 and 7.1.

Thanks!
-=Aaron

**Comment by pixelcat** [comment]
Looks like the build on this failed with:

ERROR: Failed to create usr/libexec/gcc/x86_64-alpine-linux-musl/6.2.1/cc1plus: No space left on device
ERROR: g++-6.2.1-r1: No space left on device

**Comment by csandanov** [comment]
@pixelcat I think there was just a temporarily problem on travis, please try again

**Comment by pixelcat** [comment]
Updated Pull request. Thanks :)

https://github.com/wodby/drupal-php/pull/28

**Comment by csandanov** [comment]
LDAP extension has been added https://github.com/wodby/php/blob/master/7.0/test/php_modules
