### ISSUE TITLE
Add the php APCu extension 

### ISSUE THREAD

**Issue by martinfrances107** [wodby/drupal-php#26]
I find this project really useful...

Here is my train of thought....I have been looking at way to make my drupal site more performant.

As an alternative to REDIS or MEMCACHE I have been looking at making use of 

https://www.drupal.org/project/lcache

That module has a dependency on PHP's APCu extension

Over the weekend I will try and get this working

**Comment by PavelPrischepa** [comment]
#27 Merged.

**Comment by csandanov** [comment]
APCu extension has been added (see more at https://github.com/wodby/php/blob/master/7.0/test/php_modules)
