### ISSUE TITLE
Add php-ast extension

### ISSUE THREAD

**Issue by meramo** [wodby/drupal-php#30]
Is it possible to include php-ast by the chance? It is required by a very popular static analyser Phan https://github.com/etsy/phan so I thought it might be useful to have it at hand. Thanks!

**Comment by csandanov** [comment]
Drupal console 1.0.0 RC* is not currently compatible with the latest stable drush when installing via composer https://github.com/hechoendrupal/drupal-console/issues/3249

**Comment by csandanov** [comment]
ast extension has been added to 7.0 and 7.1 tags

**Comment by meramo** [comment]
Thanks guys, you rock!
