### ISSUE TITLE
Drupal Console version ship is out of date

### ISSUE THREAD

**Issue by lslinnet** [wodby/drupal-php#31]
Drupal Console version shipped with the container is so out of date it is close to useless, it should include at least the ~1.0 version instead.

**Comment by csandanov** [comment]
Drupal console 1.0.0 RC* is not currently compatible with the latest stable drush when installing via composer hechoendrupal/drupal-console#3249

**Comment by csandanov** [comment]
The latest versions of drupal-php (7.0 and 7.2) now come with console launcher RC-16. Please note that you now have to install drupal console manually per each drupal project via composer. For more details see https://github.com/hechoendrupal/drupal-console/issues/3250
