### ISSUE TITLE
Drupal 8 issue on install due to php.ini HTTP_RAW_POST_DATA value

### ISSUE THREAD

**Issue by dameert** [wodby/drupal-php#33]
Using the docker4drupal image and getting an error on install (using nginx). Drupal offers a solution in the error message:
`Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead.`

How would I be able to modify that parameter? 
Many thanks in advance for your help.

**Comment by csandanov** [comment]
What version of PHP are you using? The option `always_populate_raw_post_data` [was removed in PHP 7.0](http://php.net/manual/en/ini.core.php). 

Just in case I've set this option to -1 in php 5.6.

**Comment by dameert** [comment]
Sorry forgot to specify! Using PHP 5.6, I'll test it out this evening!

**Comment by csandanov** [comment]
Make sure you're using non-tagged version, i.e. just `wodby/drupal-php:5.6`. Btw, what's the point of deploying D8 with 5.6? It's fully compatible with PHP 7.

**Comment by dameert** [comment]
It works & Indeed there is no good reason for 5.6 and D8 that I can think of.
