### ISSUE TITLE
Having issues with cron

### ISSUE THREAD

**Issue by webdobe** [wodby/drupal-php#34]
How do you get cron running?  Some docs say that cron auto runs every 15 minutes not seeing that happen.  I have even tried mounting a script to the 15min cron with no success.  Is there something I am missing?

Should I be running site crons from the host?  This may be a wodby/php issue.

**Comment by csandanov** [comment]
Not sure where you found the information about 15 minutes, normally you don't need cron for your local environment. Nevertheless, you can run cron by launching another php container with the overriden command like we do in [our tests](https://github.com/wodby/php/blob/master/7.1/test/docker-compose.yml#L83).
