### ISSUE TITLE
Request: Create a PHP 5.5 image

### ISSUE THREAD

**Issue by tanc** [wodby/drupal-php#35]
As Drupal still supports PHP 5.5.9+ it would be great to have a 5.5.x image to test with. For example, I'm currently having a problem with a module that appears to exhibit issues on 5.5.55 (remote server) but not on your 5.6 or 7.1 images. It would be great to be able to replicate the issue locally to feed back conclusive evidence to the module maintainer.

**Comment by BrizzleRocker** [comment]
Seconded! We are having some issue with GD Image on 5.5.9 and it would be so useful to spin up Wodby with 5.5! I'm looking into other containers but really trust Wodby.

**Comment by csandanov** [comment]
Why can't you use 5.6? 5.6 is the only one from 5.x branch that is still maintained. The only reason we have 5.3 is for compatibility with legacy Drupal 6.x. We would drop 5.3 if we could.

**Comment by BrizzleRocker** [comment]
I appreciate this is an edge case, but from the quick bit of research I was able to do yesterday there are some slight differences. I am seeing problems with my site using the PHP 5.6 image in my Docker stack. I will look around for an alternative PHP image or roll my own. Thanks for a great tool @csandanov !
