### ISSUE TITLE
Allow Drush version to be configurable.

### ISSUE THREAD

**Issue by seanBlommaert** [wodby/drupal-php#37]
When developing on the latest dev branch of Drupal (8.4.x) the symfony version is updated. This latest version does not work with Drush 8.
It would be great if the Drush version is configurable, so we could optionally use Drush 9 in the container.

**Comment by csandanov** [comment]
Nowadays, drush usually comes with drupal itself like drupal console. So, if your project is composer-based you should have drush under vendor/ dir.

**Comment by csandanov** [comment]
We now have drush launcher that will automatically use drush that comes with your composer-based project.
