### ISSUE TITLE
Drush not working via SSH

### ISSUE THREAD

**Issue by Vacilando** [wodby/drupal-php#39]
When I connect to the PHP container via SSH (in Windows) using the config mentioned in #38, drush does not work.
```
02c4fa62db6c:/var/www/html$ drush
-bash: drush: command not found
```
What am I doing wrong?

**Comment by csandanov** [comment]
What tag are you on? Should work with the latest, without stability tag, e.g. 7.1, 7.0

**Comment by Vacilando** [comment]
I am using one of the ones provided in the default docker-compose.yml on GitHub, namely 7.1-2.1.0

**Comment by csandanov** [comment]
Try 7.1, this should be fixed

**Comment by Vacilando** [comment]
OK, it works when I use the following for the sshd container:
`image: wodby/drupal-php:7.1`

Do you also plan to add it to the versions with stability tags? If so, this ticket may stay open. I let you decide.

**Comment by csandanov** [comment]
D4D 2.2.0 includes this fix.
