### ISSUE TITLE
Cannot run drush dl within container anymore (7.1)

### ISSUE THREAD

**Issue by pianomansam** [wodby/drupal-php#45]
It appears that by changing the user to www-data, I can no longer do a `drush dl` to get a new module. 

https://github.com/wodby/drupal-php/blob/496e9ac4568d1884b31e33fa50345ada29c30299/7.1/Dockerfile#L30

I realize using the root user in the container isn't the best idea, but using www-data means I cannot modify anything outside what PHP-FPM can modify.

**Comment by pianomansam** [comment]
Please note this is with Drupal 7.

**Comment by csandanov** [comment]
Why can't you download? Do you run drush inside of the php container? What are permissions/ownership of your /var/www/html? It should be owned by `www-data`. 

You should not use latest images without stability tags, also you can always switch back to 2.x.x, 3.x.x has www-data as default user.
