### ISSUE TITLE
Request: Install jpegtran

### ISSUE THREAD

**Issue by devbranch-vadym** [wodby/drupal-php#46]
Hi,

jpegtran is a well-known tool used for optimizing (mostly) and manipulating JPEG files.
Which is important if that it's used by a popular [ImageAPI Optimize](https://www.drupal.org/project/imageapi_optimize) contrib module.

Installing the tool works just fine:
```sh
apk add libjpeg-turbo-utils
```

Maybe it worths adding it to the default installation?

Thanks.

**Comment by csandanov** [comment]
Will be available with the upcoming release, thank you.

**Comment by csandanov** [comment]
The latest release `wodby/drupal-php:x.x-3.3.1` has this package installed.
