### ISSUE TITLE
Add a PHP Extension

### ISSUE THREAD

**Issue by ghalusa** [Wodby/drupal-php#5]
Kinda new to this. I'm looking to add the extension, `php5-xsl`.

Is there a way to modify the PHP build from the `docker-compose.yml` at `docker4drupal`? If not, do you happen to have any suggestions?

**Comment by PavelPrischepa** [comment]
Hi, @ghalusa 

I've added php5-xsl. It's already queued on DockerHub.

**Comment by PavelPrischepa** [comment]
The image has been built.

**Comment by ghalusa** [comment]
Confirmed. Thanks @PavelPrischepa! Much appreciated!
