### ISSUE TITLE
Getting segmentation fault error while trying to generate code coverage with PHPUnit

### ISSUE THREAD

**Issue by mxr576** [wodby/drupal-php#57]
I am getting Segmentation fault when I am trying to generate code coverage by using the drupal-php:7.1-dev-4.5.0 image. It seems there is no issue if I use drupal-php:7.2-dev-4.5.0 image so maybe this is caused by some pre-installed extension?

`vendor/bin/phpunit -c core -v --debug --filter testForm BrowserTestBaseTest core/tests/Drupal/FunctionalTests/BrowserTestBaseTest.php --coverage-php=/var/www/html/coverage.cov
`

**Comment by mxr576** [comment]
So it failed several times on a project but now it is working on an other one. Am using the same containers so this is weird. I am trying to figure out why it is failed in one place not the other one and describe how this can be reproduced.

**Comment by csandanov** [comment]
Thanks for reporting this, it would be really helpful if you provide steps how to reproduce it. Also, try using `wodby/php` images with `-debug` tag to get more details, I guess you have a core dump https://bugs.php.net/bugs-generating-backtrace.php

**Comment by csandanov** [comment]
Also, as a quick guess try disabling apcu via `PHP_APCU_ENABLED=0` when you get a segfault, see if it helps.
