### ISSUE TITLE
Omit permission issues

### ISSUE THREAD

**Issue by peperoni60** [wodby/drupal-php#6]
Normally you issue commands (drush, drupal, composer) as root user or as user 82 (if explicitly provided). But with both users you will run into permission problems as the files on the host machine are created as privileged (root) or unknown (82) user and you can't edit any of the generated / downloaded files.
You could easily avoid such problems if you add a `umask 000` in the docker entrypoint to set the file permissions accordingly (777).

**Comment by csandanov** [comment]
Drush, drupal, composer are now installed for www-data user. Also, a new [article](http://docs.docker4drupal.org/en/latest/permissions/) was added on how to avoid permissions problems.

**Comment by peperoni60** [comment]
I have read the article and do not agree with you. Do you really mean I should patch **my** system to avoid permission problems that occur through **your** system?

**Comment by csandanov** [comment]
Our images are based on official php images (alpine linux). UID/GID 82 is a standard for www-data user in alpine linux and [hardcoded in the official php image](https://github.com/docker-library/php/blob/ec02e1bcf1196ed3f8b74ecc956cf81554e32db8/7.1/fpm/alpine/Dockerfile#L27). If you don't want to add a group on your host machine, you can always change permissions on the files directory. 

Also, you can build your own image based on ours and re-create www-data user with gid/uid matching your host user or, as you suggested, set umask in the entrypoint / init script.
