### ISSUE TITLE
Add php-rdkafka php extension

### ISSUE THREAD

**Issue by sailorphoenix** [wodby/drupal-php#60]
Hello!

I publish an issue to know if it possibles to add php-rdkafka extension to drupal-php image? I tried on my own without success. If we can add this on the main image or just describe me the process to add it on my custom image, I will be very grateful.

PHP Version : 7.1
ext-rdkafka wanted : 3.0 at least

Thanks a lot!

**Comment by csandanov** [comment]
Yes, I think we can add it to wodby/php, do you mind moving your issue there?

**Comment by sailorphoenix** [comment]
Great! I do that right now :) Thanks for your answer!
