### ISSUE TITLE
unable to find docker-entrypoint.sh

### ISSUE THREAD

**Issue by hareeshrao4839** [wodby/drupal-php#61]
Hi, in dockerhub dockerfile contains docker-entrypoint.sh but i couldn't find in github what your you mentioned in repoinfo . 

COPY docker-entrypoint.sh /usr/local/bin/
CMD docker-entrypoint.sh

please help me out  
https://hub.docker.com/r/wodby/drupal-php/~/dockerfile/

**Comment by csandanov** [comment]
That's a docker hub bug, they show the old version of the dockerfile since the time we used docker hub to build images. We've been building docker images on travisci for a while and pushing them to docker hub. You can find the actual dockerfile in these repos, see README
