### ISSUE TITLE
sudo password for user wodby

### ISSUE THREAD

**Issue by sprklinginfo** [wodby/drupal-php#67]
Hi there,
If I _docker-compose exec php sh_ into the php container, I access the container as the user wodby. How can I become root user? I tried with _sudo su -_ but don't know the sudo password for this user.
Thanks,

**Comment by csandanov** [comment]
Use `dev` version of the image:
```shell
$ docker run --rm -ti wodby/drupal-php:dev sh                                                                                                  
wodby@php.container:/var/www/html $ sudo su
root@php.container:/var/www/html $
```

**Comment by davidwhthomas** [comment]
Hi @csandanov sorry to comment on a closed issue, but is there anyway to reset or set the sudo/root password when not using the dev image?

**Comment by superromeo** [comment]
> Use `dev` version of the image:
> 
> ```shell
> $ docker run --rm -ti wodby/drupal-php:dev sh                                                                                                  
> wodby@php.container:/var/www/html $ sudo su
> root@php.container:/var/www/html $
> ```

Sorry, but I think it's inconvenient.
Maybe is there another way? Just use wodby password?

**Comment by autn** [comment]
+1, I also need the wodby password for "no-dev" version.

**Comment by superromeo** [comment]
What I should change in my `.env` or `docker-compose.yml` files to use dev version of the image?
