### ISSUE TITLE
DRUPAL8_REVERSE_PROXY_ADDRESSES not working?

### ISSUE THREAD

**Issue by fy1128** [wodby/drupal-php#68]
added docker environments: `DRUPAL8_REVERSE_PROXY_ADDRESSES:0.0.0.0/0`

The container has this env defined.
But `$_SERVER[‘DRUPAL8_REVERSE_PROXY_ADDRESSES’]` in `wodby.settings.php` gets null.

**Comment by PavelPrischepa** [comment]
Solved in #69
