### ISSUE TITLE
Is this a typo error?

### ISSUE THREAD

**Issue by fy1128** [wodby/drupal-php#69]
code in [wodby.settings.php.tmpl #54 ](https://github.com/wodby/drupal-php/blob/6f00cf16d6ed070b652dc63122459c350bd16362/7/templates/drupal8.settings.php.tmpl#L54):

```php
    if (isset($_SERVER['DRUPAL_REVERSE_PROXY_ADDRESSES'])) {
        $proxies = array_merge(
            array_filter(
                array_map(function ($item) {
                    return trim($item);
                }, explode(',', (string)$_SERVER['DRUPAL8_REVERSE_PROXY_ADDRESSES']))
            ),
            $proxies
        );
    }
```
`DRUPAL_REVERSE_PROXY_ADDRESSES` and `DRUPAL8_REVERSE_PROXY_ADDRESSES`.

**Comment by csandanov** [comment]
Yes, it's a typo. Thank you for reporting this! The env var now called `DRUPAL_REVERSE_PROXY_ADDRESSES`. And D7 supports it too
