### ISSUE TITLE
Composer update takes 15 minutes

### ISSUE THREAD

**Issue by johandenhollander** [wodby/drupal-php#75]
Using the php 7.2 image (or 7.3 / 7.4) and noticed that composer update takes forever.
After much digging around I baked a new image for drupal-php with the latest composer version.

Composer version 1.10.10 2020-08-03 11:35:19 | 15 minutes
Composer version 1.10.13 2020-09-09 11:46:34 | 3 minutes

Thought I let you know this. So others should not also spend a lot of time waiting behind their terminals.

Bye!

**Comment by johandenhollander** [comment]
https://blog.packagist.com/composer-2-0-is-now-available/

**Comment by csandanov** [comment]
composer + mutagen 2.0 should solve this problem
