### ISSUE TITLE
Return drush launcher to PHP 8

### ISSUE THREAD

**Issue by csandanov** [wodby/drupal-php#78]
Currently prevented by drush launcher dependencies incompatibility https://github.com/drush-ops/drush-launcher/issues/84

**Comment by gene-miller** [comment]
Any progress here?

Seems like this might be the cause of issues with Drupal 9.3 on wodby/drupal-php:8.1-4.31.2 ?

```
Deprecated: Return type of HumbugBox3111\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator()
```

**Comment by csandanov** [comment]
drush launcher installation was returned for drupal 8 about a year ago
