### ISSUE TITLE
Update drush launcher to 0.8.0

### ISSUE THREAD

**Issue by csandanov** [wodby/drupal-php#79]
Currently has some memory issues that result in tests failures https://github.com/drush-ops/drush-launcher/issues/82

**Comment by webflo** [comment]
@csandanov Hi, could you explain how to run the tests? Would like to debug it ... Thanks!

**Comment by csandanov** [comment]
- Update drush launcher version to 0.8.0 in Dockerfile on [this line](https://github.com/wodby/drupal-php/blob/master/Dockerfile#L23)
- Since we install drush launcher only for PHP 7.x run `PHP_VER=7.4 make` from the repository root to build the image
- Comment [this line](https://github.com/wodby/drupal-php/blob/master/Makefile#L51) to disable Drupal 8 tests in Makefile since the issue only reproduced in Drupal 7 
- Then  run `PHP_VER=7.4 make test`

Here's the failure [example](https://github.com/wodby/drupal-php/runs/1530372756?check_suite_focus=true#step:3:2013) from github actions. It fails on `drush status --format=yaml`. It first runs drupal 8 tests, then drupal 7, it fails only on Drupal 7 tests that located at https://github.com/wodby/drupal-php/blob/master/tests/7/tests.sh

You probably can just run `make shell` to launch and access the container after the image is built without running all tests

**Comment by webflo** [comment]
https://github.com/box-project/box/issues/512

**Comment by back-2-95** [comment]
Included drush launcher is already 0.10.1 so maybe this issue can be closed?
