### ISSUE TITLE
Add rsync to this image

### ISSUE THREAD

**Issue by sedurzu** [Wodby/drupal-php#8]
Hi.
I'm using this image (with docker4drupal compose file) for my drupal projects.
I'm working also with external services like Pantheon so I need to use drush commands like sql-sync.
Everything works but on the drupal-php image should be installed also rsync, used by drush to copy sql dump from remote host.

Is it possible?

Thanks a lot,
Sergio

**Comment by PavelPrischepa** [comment]
Yes, sure. I've added rsync efe62998a4ee36dc5631f8d6f33325e981d2bd4e feel free to use.

**Comment by sedurzu** [comment]
Ok, thanks, works :)
