### ISSUE TITLE
Included drush-launcher has dependency which causes warnings with PHP 8.2

### ISSUE THREAD

**Issue by back-2-95** [wodby/drupal-php#96]
See https://github.com/drush-ops/drush-launcher/issues/102

The project has not been updated since Feb 2022 and cannot see much answer on the issues either. I wonder if drush-launcher is active anymore...

_Originally posted by @back-2-95 in https://github.com/wodby/drupal-php/issues/95#issuecomment-1377231343_

**Comment by csandanov** [comment]
Fixed in #98
