### ISSUE TITLE
Deprecate and plan the removal of Drush Launcher

### ISSUE THREAD

**Issue by mxr576** [wodby/drupal-php#98]
Triggered by [the recent presentation](https://docs.google.com/presentation/d/14euH9Knf9Eaclw9PnVorfhxrFX4Ktph6ZdexBrWNWPc/edit#slide=id.g2161bd1e163_0_65) on DrupalCon Pittsburg.

**Drush 11 got an EOL date: 2023 November**. It was also marked as not recommended for Drupal 10. The recommended version is Drush 12.

Drush Launcher is not (officially) compatible with Drush 12 at this moment and it may not be compatible in the future, rather Drush 12 is going to fail nicely when it is called via Drush Launcher: https://github.com/drush-ops/drush-launcher/issues/105

**Comment by csandanov** [comment]
we keep drupal launcher because Drupal 7 is still supported (and EOL has recently been postponed), and many Drupal 7 projects are still not composer-based so we install global drush and drush launcher

**Comment by gene-miller** [comment]
Hi Chingis, have we got a solution for this? 
drupal/core 10.2 requires drush 12.4

```
    "conflict": {
        "drush/drush": "<12.4.3"
    },
```
